Array performs math, list dont

In [3]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
print(list1 + list2)

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr2 - arr1)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 * arr2)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr2 / arr1)


[1, 2, 3, 4, 5, 6]
[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]
